apiVersion: 1.0.0
kind: Plugin
metadata:
  name: MapQuest Geocoding API Service
  description: MapQuest Geocoding API Service Plugin for the Reekoh IoT platform
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Service
  price: 0
  tags:
    - service
    - mapquest
    - geocoding
    
  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      apikey:
        label: MapQuest API Key
        type: Password
        maxLength: 1000
        required: true
        help: Enter the API Key provided by MapQuest.
      geocodingType:
        label: Geocoding Type
        type: String
        maxLength: 1000
        enum:
        - Forward
        - Reverse
        required: false
        default: Reverse
        help: "(Optional) The type of geocoding to be done. Default 'Reverse'."
